# MDD Symptoms meta analysis

Set up in process meta-analysis so that leave-one-out (LOO) can be swiftly generated.

In [1]:
import polars as pl
import glob
from pathlib import Path

Symptom references

In [2]:
symptom_reference_tab = """
MDD1;depressed;Depressed mood most of the day, nearly every day
MDD2;anhedonia;Markedly diminished interest or pleasure in all, or almost all, activities most of the day, nearly every day
MDD3;weightChange;Significant change in weight or appetite
MDD3a;weightLoss;Significant weight loss or decrease in appetite
MDD3b;weightGain;Significant weight gain or increase in appetite
MDD4;sleepChange;Sleeping too much or not sleeping enough
MDD4a;sleepProb;Insomnia nearly every day
MDD4b;sleepMore;Hypersomnia nearly every day
MDD5;psychomotor;Changes in speed/amount of moving or speaking
MDD5a;psychomotorFast;Psychomotor agitation nearly every day
MDD5b;psychomotorSlow;Psychomotor retardation nearly every day
MDD6;fatigue;Fatigue or loss of energy nearly every day
MDD7;worthless;Feelings of worthlessness or excessive or inappropriate guilt
MDD8;concentration;Diminished ability to think or concentrate, or indecisiveness
MDD9;death;Recurrent thoughts of death or suicide or a suicide attempt or a specific plan for attempting suicide
"""

symptom_reference_dat = [line.split(';') for line in symptom_reference_tab.strip().split('\n')]
references = [symp[0] for symp in symptom_reference_dat]
abbrevs = [symp[1] for symp in symptom_reference_dat]
descriptions = [symp[0] for symp in symptom_reference_dat]
#dsm_mdd_symptoms_reference_df = pd.DataFrame(symptom_reference_dat,
#    columns=['Reference', 'Symptom Abbrev.', 'Description'])
dsm_mdd_symptoms_reference_df = pl.DataFrame(
    {
        "reference": references,
        "abbrev": abbrevs,
        "description": descriptions
    }
)
dsm_mdd_symptoms_reference_df

shape: (15, 3)
┌───────────┬─────────────────┬─────────────┐
│ reference ┆ abbrev          ┆ description │
│ ---       ┆ ---             ┆ ---         │
│ str       ┆ str             ┆ str         │
╞═══════════╪═════════════════╪═════════════╡
│ MDD1      ┆ depressed       ┆ MDD1        │
│ MDD2      ┆ anhedonia       ┆ MDD2        │
│ MDD3      ┆ weightChange    ┆ MDD3        │
│ MDD3a     ┆ weightLoss      ┆ MDD3a       │
│ MDD3b     ┆ weightGain      ┆ MDD3b       │
│ …         ┆ …               ┆ …           │
│ MDD5b     ┆ psychomotorSlow ┆ MDD5b       │
│ MDD6      ┆ fatigue         ┆ MDD6        │
│ MDD7      ┆ worthless       ┆ MDD7        │
│ MDD8      ┆ concentration   ┆ MDD8        │
│ MDD9      ┆ death           ┆ MDD9        │
└───────────┴─────────────────┴─────────────┘

Read list of cohorts and groupings

In [3]:
cohorts_df = pl.read_csv("meta/cohort_alignment.txt", separator="\t")
cohorts_reference_df = cohorts_df.join(dsm_mdd_symptoms_reference_df, on="reference")
cohorts_reference_df

shape: (244, 7)
┌─────────────────────────────────┬───────┬────────┬───────┬───────────┬────────────┬─────────────┐
│ filename                        ┆ study ┆ cohort ┆ group ┆ reference ┆ abbrev     ┆ description │
│ ---                             ┆ ---   ┆ ---    ┆ ---   ┆ ---       ┆ ---        ┆ ---         │
│ str                             ┆ str   ┆ str    ┆ str   ┆ str       ┆ str        ┆ str         │
╞═════════════════════════════════╪═══════╪════════╪═══════╪═══════════╪════════════╪═════════════╡
│ daner_MDD1_bidi1.gz             ┆ bidi1 ┆ PGC    ┆ Clin  ┆ MDD1      ┆ depressed  ┆ MDD1        │
│ daner_MDD1_gep3.gz              ┆ gep3  ┆ PGC    ┆ Clin  ┆ MDD1      ┆ depressed  ┆ MDD1        │
│ daner_MDD1_nes1.gz              ┆ nes1  ┆ PGC    ┆ Clin  ┆ MDD1      ┆ depressed  ┆ MDD1        │
│ daner_MDD1_rot4.gz              ┆ rot4  ┆ PGC    ┆ Clin  ┆ MDD1      ┆ depressed  ┆ MDD1        │
│ daner_MDD1_stm2.gz              ┆ stm2  ┆ PGC    ┆ Clin  ┆ MDD1      ┆ depressed  ┆ MDD1        │
│ …                               ┆ …     ┆ …      ┆ …     ┆ …         ┆ …          ┆ …           │
│ daner_dichotomized_Pessimistic… ┆ janpy ┆ janpy  ┆ Clin  ┆ MDD7      ┆ worthless  ┆ MDD7        │
│ daner_dichotomized_Reduced_App… ┆ janpy ┆ janpy  ┆ Clin  ┆ MDD3a     ┆ weightLoss ┆ MDD3a       │
│ daner_dichotomized_Reduced_Sle… ┆ janpy ┆ janpy  ┆ Clin  ┆ MDD4a     ┆ sleepProb  ┆ MDD4a       │
│ daner_dichotomized_Sadness_2.m… ┆ janpy ┆ janpy  ┆ Clin  ┆ MDD1      ┆ depressed  ┆ MDD1        │
│ daner_dichotomized_Suicidal_Th… ┆ janpy ┆ janpy  ┆ Clin  ┆ MDD9      ┆ death      ┆ MDD9        │
└─────────────────────────────────┴───────┴────────┴───────┴───────────┴────────────┴─────────────┘

Mark information with dataset name to match tidied sumstats, and group into meta-analysis sets.

In [4]:
cohorts_datasets = cohorts_reference_df.with_columns(
    (pl.col("study") + "-" + pl.col("group") + "-" + pl.col("reference") + "-ref").alias("dataset"),
    (pl.col("group") + "-" + pl.col("reference") + "_" + pl.col("abbrev")).alias("metaset")
)

Dataset list for primary group/symptom combinations.

In [5]:
metasets = (
    cohorts_datasets
    .select(pl.col("dataset"), pl.col("metaset"))
    .unique()
)
metasets

shape: (244, 2)
┌────────────────────────┬────────────────────────────┐
│ dataset                ┆ metaset                    │
│ ---                    ┆ ---                        │
│ str                    ┆ str                        │
╞════════════════════════╪════════════════════════════╡
│ bidi1-Clin-MDD8-ref    ┆ Clin-MDD8_concentration    │
│ EstBB-Comm-MDD1-ref    ┆ Comm-MDD1_depressed        │
│ boma-Clin-MDD4b-ref    ┆ Clin-MDD4b_sleepMore       │
│ GenScot-Clin-MDD3b-ref ┆ Clin-MDD3b_weightGain      │
│ AGDS-Clin-MDD3a-ref    ┆ Clin-MDD3a_weightLoss      │
│ …                      ┆ …                          │
│ EstBB-Comm-MDD6-ref    ┆ Comm-MDD6_fatigue          │
│ col3-Clin-MDD5b-ref    ┆ Clin-MDD5b_psychomotorSlow │
│ rde4-Clin-MDD5b-ref    ┆ Clin-MDD5b_psychomotorSlow │
│ janpy-Clin-MDD9-ref    ┆ Clin-MDD9_death            │
│ stm2-Clin-MDD4b-ref    ┆ Clin-MDD4b_sleepMore       │
└────────────────────────┴────────────────────────────┘

Open tidied sumstats. Cast `CHR` column to string so the type is the same across datasets. Add dataset name as a column and assign to metasets (only process Community cohorts metasets for now).

In [6]:
sumstats_paths = glob.glob("sumstats/tidy/*-Comm-*.parquet")
sumstats = (
    pl.concat(
        [pl.scan_parquet(path).cast({"CHR": pl.String}).with_columns(pl.lit(Path(path).stem).alias("dataset")) for path in sumstats_paths],
        how = "vertical"
    ).join(metasets.lazy(), on = "dataset", how = "inner")
)

Weight statistics in preperation for meta-analysis.

In [7]:
weights = (
        sumstats.with_columns(
            (1 / (pl.col("SE") ** 2)).alias("ivw")
        )
        .with_columns(
            (pl.col("B") * pl.col("ivw")).alias("wBETA"),
            (pl.col("INFO") * pl.col("N")).alias("wINFO"),
            (pl.col("EAF") * pl.col("CaseN")).alias("wEAF")
        )
)

Perform meta-analysis grouped by metaset and variant

In [8]:
meta = (
  weights
  .group_by("metaset", "CHR", "POS_38", "POS_37", "RSID", "EffectAllele", "OtherAllele")
  .agg(
      (pl.sum("wBETA") /  pl.sum("ivw")).exp().alias("OR"),
      (1 / pl.sum("ivw")).sqrt().alias("LOG_OR_SE"),
      (pl.sum("wINFO") / pl.sum("N")).alias("INFO"),
      (pl.sum("wEAF") / pl.sum("CaseN")).alias("EAF"),
      pl.sum("CaseN"),
      pl.sum("ControlN"),
      pl.sum("EffectiveN")
  )
)

Calculate meta-analysis and sink dataset.

In [9]:
meta.sink_parquet(
  pl.PartitionBy("meta/tidy", key = ["metaset", "CHR"]),
  mkdir = True
)